customColorSchemes:
  - name: One Dark Pro Darker
    foreground: '#ABB2BF'
    background: '#23272e'
    cursor: '#bbbbbb'
    colors:
      - '#3f4451'
      - '#e05561'
      - '#8cc265'
      - '#d18f52'
      - '#4aa5f0'
      - '#c162de'
      - '#42b3c2'
      - '#d7dae0'
      - '#4f5666'
      - '#ff616e'
      - '#a5e075'
      - '#f0a45d'
      - '#4dc4ff'
      - '#de73ff'
      - '#4cd1e0'
      - '#e6e6e6'
    selection: '#abb2bf30'